### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by pioneerAlone** [QianMoth/copen_rtt#1]
Hello,

#1 example 只是slave 功能？，有主机的范例吗
#2 有没有rtthread 移植好的工程 可以参考下
#3 另外字典对象是怎么生成的，手写，还是用festival 那个字典对象工具

**Comment by zmoth** [comment]
1. example 中slaveinfo 应该是master的例程，用来获取所有的slave的信息
2. 没有，
3. 应该是生成的，具体什么工具有些忘记了。

这个项目很久没有更新了，功能也是不完善且没有经过验证的，学习可以，欢迎提交PR

**Comment by pioneerAlone** [comment]
多谢，我先学习下。
